export const GET_ALL_INGREDIENTS = 'GET_ALL_INGREDIENTS';
export const GET_INGREDIENT = 'GET_INGREDIENT';
export const GET_INGREDIENT_BY_RECIPE = 'GET_INGREDIENT_BY_RECIPE';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';

export const GET_ALL_MESURE_UNITIES = 'GET_ALL_MESURE_UNITIES';
export const GET_MESURE_UNITY = 'GET_MESURE_UNITY';
export const ADD_MESURE_UNITY = 'ADD_MESURE_UNITY';
export const UPDATE_MESURE_UNITY = 'UPDATE_MESURE_UNITY';
export const DELETE_MESURE_UNITY = 'DELETE_MESURE_UNITY';

export const GET_ALL_RECIPETYPES = 'GET_ALL_RECIPETYPES';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const CLEAR_FILTER = 'CLEAR_FILTER';
